name: Test Find Lowest Number
on: [push]
jobs: 
  test_find_lowest_number:
    name: Test Find Lowest Number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: 
        python-version: "3.10"
    - name: Produce Actual Output (10 Numbers)
      run: python find_lowest_number.py numbers.txt output1.txt
    - name: Compare Expected to Actual (10 Numbers)
      run: diff expected1.txt output1.txt
    - name: Produce Actual Output (1 Number)
      run: python find_lowest_number.py number.txt output2.txt
    - name: Compare Expected to Actual (1 Number)
      run: diff expected2.txt output2.txt
    - name: Produce Actual Output (Blank File)
      run: python find_lowest_number.py blank.txt output3.txt
    - name: Compare Expected To Actual (Blank File)
      run: diff expected3.txt output3.txt
