name: Test Find Lowest Number
on: [push]
jobs: 
  test_find_lowest_number:
    name: Test Find Lowest Number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: 
        python-version: "3.10"
    - name: Produce Actual Output (10 Numbers)
      run: python find_lowest_number.py test1_input.txt output1.txt
    - name: Compare Expected to Actual (10 Numbers)
      run: diff test1_expected.txt output1.txt
    - name: Produce Actual Output (1 Number)
      run: python find_lowest_number.py test2_input.txt output2.txt
    - name: Compare Expected to Actual (1 Number)
      run: diff test2_expected.txt output2.txt
    - name: Produce Actual Output (Blank File)
      run: python find_lowest_number.py test3_input.txt output3.txt
    - name: Compare Expected To Actual (Blank File)
      run: diff test3_expected.txt output3.txt
